pipeline {
    agent any

    options {
        timestamps()
    }

    tools {
        nodejs "node20"
    }

    parameters {
        booleanParam(
            name: 'PROVISION_INFRA',
            defaultValue: false,
            description: 'Provision AWS infra (will be destroyed after verification)'
        )
    }

    environment {
        AWS_REGION = "ap-south-1"
        PROJECT    = "doctor-app"
        ENV        = "dev"
        SONAR_TOKEN = credentials('sonar-token-doc')
    }

    stages {

        stage("Preflight Checks") {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
                ]) {
                    script {
                        load "Jenkins/pipelines/preflight.groovy"
                    }
                }
            }
        }

        stage("CI") {
            steps {
                script {
                    load "Jenkins/pipelines/ci.groovy"
                }
            }
        }

        // stage("Provision / Update Infra") {
        //     when {
        //         expression { params.PROVISION_INFRA }
        //     }
        //     steps {
        //         withCredentials([
        //             [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
        //         ]) {
        //             script {
        //                 load "Jenkins/pipelines/infra.groovy"
        //             }
        //         }
        //     }
        // }

        // stage("Detect Active Color") {
        //     when {
        //         expression { params.PROVISION_INFRA }
        //     }
        //     steps {
        //         withCredentials([
        //             [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
        //         ]) {
        //             script {
        //                 load "Jenkins/pipelines/detect_color.groovy"
        //             }
        //         }
        //     }
        // }

        // stage("Deploy New Version") {
        //     when {
        //         expression { params.PROVISION_INFRA }
        //     }
        //     steps {
        //         withCredentials([
        //             [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
        //         ]) {
        //             script {
        //                 load "Jenkins/pipelines/deploy_green.groovy"
        //             }
        //         }
        //     }
        // }

        // stage("Health Check") {
        //     when {
        //         expression { params.PROVISION_INFRA }
        //     }
        //     steps {
        //         withCredentials([
        //             [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
        //         ]) {
        //             script {
        //                 load "Jenkins/pipelines/health_check.groovy"
        //             }
        //         }
        //     }
        // }

        // stage("Switch Traffic") {
        //     when {
        //         expression { params.PROVISION_INFRA }
        //     }
        //     steps {
        //         withCredentials([
        //             [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
        //         ]) {
        //             script {
        //                 load "Jenkins/pipelines/switch_traffic.groovy"
        //             }
        //         }
        //     }
        // }

        // stage("Cleanup Old Version") {
        //     when {
        //         expression { params.PROVISION_INFRA }
        //     }
        //     steps {
        //         withCredentials([
        //             [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
        //         ]) {
        //             script {
        //                 load "Jenkins/pipelines/cleanup_blue.groovy"
        //             }
        //         }
        //     }
        // }

        // stage("🧪 Manual Verification (Screenshots)") {
        //     when {
        //         expression { params.PROVISION_INFRA }
        //     }
        //     steps {
        //         script {
        //             load "Jenkins/pipelines/manual_verify.groovy"
        //         }
        //     }
        // }

        // stage("🧹 Destroy Infra (Cost Safety)") {
        //     when {
        //         expression { params.PROVISION_INFRA }
        //     }
        //     steps {
        //         withCredentials([
        //             [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
        //         ]) {
        //             script {
        //                 load "Jenkins/pipelines/destroy_infra.groovy"
        //             }
        //         }
        //     }
        // }
    }

    post {
        success {
            echo "✅ Guardrails before Production"
        }

        failure {
            echo "❌ Pipeline Failed – Cleaning Infra"
            script {
                if (params.PROVISION_INFRA) {
                    load "Jenkins/pipelines/destroy_infra.groovy"
                }
            }
        }
    }
}
