pipeline {
    agent any

    options {
        timestamps()
    }

    tools {
        nodejs "node20"
    }

   parameters {
    booleanParam(
        name: 'PROVISION_INFRA',
        defaultValue: false,
        description: 'Provision AWS infra (will be destroyed after verification)'
    )
    booleanParam(
        name: 'DESTROY_ALL',
        defaultValue: false,
        description: 'Destroy ALL infra (color → base → bootstrap)'
    )
}


    environment {
        AWS_REGION = "ap-south-1"
        PROJECT    = "doctor-app"
        ENV        = "dev"
        SONAR_TOKEN = credentials('sonar-token-doc')
        DOCKERHUB   = credentials('dockerhub-cred')
        DOCKER_REPO = "sahil0724"
        TF_CLI_ARGS = "-no-color"
        // NEW_COLOR = "${params.NEW_COLOR}"
    }

    stages {

        stage("Preflight Checks") {
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
                ]) {
                    script {
                        load "Jenkins/pipelines/preflight.groovy"
                    }
                }
            }
        }

        stage("CI") {
            steps {
                script {
                    load "Jenkins/pipelines/ci.groovy"
                }
            }
        }

          stage("Provisioning BASE and Bootstrap Infra ") {
              when {
                  expression { params.PROVISION_INFRA }
              }
              steps {
                  withCredentials([
                      [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
                  ]) {
                      script {
                          load "Jenkins/pipelines/infra.groovy"
                      }
                  }
              }
          }

          stage("Detect Active Color") {
              when {
                  expression { params.PROVISION_INFRA }
              }
              steps {
                  withCredentials([
                      [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
                  ]) {
                      script {
                          load "Jenkins/pipelines/detect_color.groovy"
                      }
                  }
              }
          }

          stage("Deploy New Version") {
              when {
                  expression { params.PROVISION_INFRA }
              }
              steps {
                  withCredentials([
                      [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
                  ]) {
                      script {
                          load "Jenkins/pipelines/deploy_green.groovy"
                      }
                  }
              }
          }


           stage("Wait for SSM To be Ready") {
            when {
                expression { params.PROVISION_INFRA }
            }
            steps {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
                ]) {
                    script {
                        load "Jenkins/pipelines/wait_for_ssm.groovy"
                    }
                }
            }
        }

        stage("Ansible Deployment") {
    when {
        expression { params.PROVISION_INFRA }
    }
    steps {
        withCredentials([
            [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
        ]) {
            script {
                load "Jenkins/pipelines/app_deploy_ansible.groovy"
            }
        }
    }
}
 

          stage("Health Check") {
              when {
                  expression { params.PROVISION_INFRA }
              }
              steps {
                  withCredentials([
                      [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
                  ]) {
                      script {
                          load "Jenkins/pipelines/health_check.groovy"
                      }
                  }
              }
          }

          stage("Switch Traffic") {
              when {
                  expression { params.PROVISION_INFRA }
              }
          steps {
              withCredentials([
                      [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
              ]) {
                      script {
                          load "Jenkins/pipelines/switch_traffic.groovy"
                      }
                  }
              }
          }

        //   stage("Cleanup Old Version") {
        //       when {
        //       expression { params.PROVISION_INFRA }
        //       }
        //       steps {
        //           withCredentials([
        //               [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
        //           ]) {
        //               script {
        //                   load "Jenkins/pipelines/cleanup_blue.groovy"
        //               }
        //           }
        //       }
        //   }

      stage("🧪 Manual Verification (Screenshots)") {
              when {
                  expression { params.PROVISION_INFRA }
              }
          steps {
                  script {
                      load "Jenkins/pipelines/manual_verify.groovy"
                  }
              }
          }

          stage("🧹 Destroy Infra (Cost Safety)") {
              when {
                  expression { params.PROVISION_INFRA }
              }
              steps {
                  withCredentials([
                      [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
                  ]) {
                      script {
                          load "Jenkins/pipelines/destroy_infra.groovy"
                      }
                  }
              }
          }
    }

   post {
    success {
        echo "✅ Blue Green Deployment is Successfully Done...."
    }

    failure {
        echo "❌ Pipeline Failed – Cleaning Infra"

        script {
            if (params.PROVISION_INFRA) {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
                ]) {
                    load "Jenkins/pipelines/destroy_infra.groovy"
                }
            } else {
                echo "ℹ️ Infra provisioning was disabled. Skipping cleanup."
            }
        }
    }

    aborted {
        echo "⚠️ Pipeline Aborted – Cleaning Infra"

        script {
            if (params.PROVISION_INFRA) {
                withCredentials([
                    [$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-creds']
                ]) {
                    load "Jenkins/pipelines/destroy_infra.groovy"
                }
            }
        }
    }
}

}
